import json
import subprocess
import sys

def create_github_issue(title, body):
    command = ["gh", "issue", "create", "--title", title, "--body", body, "--label", "security,automated-finding"]   # Uses the GitHub CLI (gh) to create an issue
    try:
        subprocess.run(command, check=True)
        print(f"Created issue: {title}")
    except subprocess.CalledProcessError as e:
        print(f"Failed to create issue: {e}")

def parse_semgrep_results():
    try:
        with open('semgrep.json', 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        print("semgrep.json not found. Exiting.")
        sys.exit(0)

    results = data.get('results', [])
    if not results:
        print("No vulnerabilities found! Great job.")
        return

    for finding in results:
        rule_id = finding.get('check_id', 'Unknown Rule')
        path = finding.get('path', 'Unknown File')
        line = finding.get('start', {}).get('line', 'Unknown Line')
        message = finding.get('extra', {}).get('message', 'No details provided.')
        severity = finding.get('extra', {}).get('severity', 'UNKNOWN')

        title = f"[Automated Security Alert] {severity}: {rule_id} in {path}"
        body = (
            f"### Automated Security Finding\n"
            f"**File:** `{path}`\n"
            f"**Line:** {line}\n"
            f"**Severity:** {severity}\n\n"
            f"**Details:**\n> {message}\n\n"
            f"*This ticket was automatically generated by the DevSecOps CI/CD pipeline.*"
        )
        
        create_github_issue(title, body)

if __name__ == "__main__":
    parse_semgrep_results()